### ISSUE TITLE
Implementation git plugin for conventional commits

### ISSUE THREAD

**Issue by anasinnyk** [conventional-commits/conventionalcommits.org#105]
Hi all,
I try to implement git plugin for easily using conventional commits in our company, maybe you have some requirements or proposition.
It's awesome if you can provide a link to my [repository](https://github.com/anasinnyk/git-convenient) in your documentation.
Best regards

**Comment by damianopetrungaro** [comment]
Hey @anasinnyk feel free to open a PR, and edit the `next` version of the specs 😄

**Comment by damianopetrungaro** [comment]
Having some documentation about the tool will be awesome too 😄

**Comment by damianopetrungaro** [comment]
@andrewrynhard As I said to @anasinnyk , feel free to open a PR and add it 😄

**Comment by andrewrynhard** [comment]
@damianopetrungaro Done 😄 #112.

**Comment by bcoe** [comment]
closing as inactive, will happily accept PRs for new tooling any time :+1:
