### ISSUE TITLE
PT-br language

### ISSUE THREAD

**Issue by joao-alberto** [conventional-commits/conventionalcommits.org#111]
Can I contribute to project translating it to brazilian portuguese?

**Comment by bcoe** [comment]
@joao-alberto would very much appreciate the translation. Perhaps @damianopetrungaro can help coordinate? He's been working on landing a new version of the website.

**Comment by damianopetrungaro** [comment]
Here I am!
Sure @joao-alberto any new translation is welcome!

This is how you can add a translation: https://github.com/conventional-commits/conventionalcommits.org#adding-a-translation

If you have any doubt feel free to reach us! ty for your time!

**Comment by damianopetrungaro** [comment]
Any news @joao-alberto ?

**Comment by bcoe** [comment]
@joao-alberto echoing @damianopetrungaro, a Portuguese translation would be awesome for the community if you eventually have the time.

Let us know in slack if you need any help getting started:

http://devtoolscommunity.herokuapp.com/

**Comment by fernandoseguim** [comment]
I have the interest to collaborate with this project. @ joao-alberto and @damianopetrungaro, how are going the pt-br translation?

**Comment by damianopetrungaro** [comment]
@fernandoseguim  I don't see any branch or PR by @joao-alberto 

So feel free to start it :)

**Comment by ivanrosolen** [comment]
Hello!

Finished adding pt-br language, but on the FAQ section there's a ref to `@jameswomack/conventional-commit-spec`, but I couldn't find it.

Am I missing something or is it better to change this?

**Comment by bcoe** [comment]
@ivanrosolen I think this was just an example that @jameswomack used when him and I drafted the spec, i.e., it's not a real module.

**Comment by danielnass** [comment]
I have added the v1.0.0 translated version to pt-BR. Contributions are very welcome 🎉

Still draft, but will finish right away https://github.com/conventional-commits/conventionalcommits.org/pull/309

**Comment by danielnass** [comment]
@damianopetrungaro as the Brazilian Portuguese v1.0.0 (#309) was released, this issue could be close 😄
