### ISSUE TITLE
Dependency Management

### ISSUE THREAD

**Issue by hutson** [conventional-commits/conventionalcommits.org#127]
Since the _theme_ for conventional-commits uses npm dependencies, could we please connect this repository to one of the available dependency management platforms out there to keep those dependencies updated?

**Comment by damianopetrungaro** [comment]
I am not a frontend developer, so I need to invest some hours in order to do it.
Is anyone more skilled than me and can take care of it?

**Comment by damianopetrungaro** [comment]
@hutson we do have GitHub that notify us in case of the security issues and we need to update the dependencies to fix it.

Do you think is it enough or do you prefer to re-open this?
