### ISSUE TITLE
Summary Button

### ISSUE THREAD

**Issue by hutson** [conventional-commits/conventionalcommits.org#131]
On the landing page for Conventional Commits there are two buttons near the center of the page;  _Read the specs_ and _GitHub_. As demonstrated in #80, part of our community feels the summary plays a vital role in quickly on-boarding engineering organizations with the convention, and ensuring a high level of consistent adherence to the convention.

Could we further help teams by providing a button on the landing page that links to the _Summary_ instead of just the specification?

**Comment by bcoe** [comment]
I like this idea, I might opt for the buttons:

`[Quick Summary] [Full Specification] [:octocat: Contribute]`

**Comment by hutson** [comment]
Personally, I like the text. The distinction, at least to me, is quite clear between `Quick` and `Full`.
