### ISSUE TITLE
i18n: provide Quick Summary translations for other languages

### ISSUE THREAD

**Issue by SimonKienzler** [conventional-commits/conventionalcommits.org#140]
The summary button labelled "Quick Summary", introduced in PR #138, needs to be translated to other languages that are supported.

**Comment by damianopetrungaro** [comment]
@SimonKienzler  do you want to work on this?

**Comment by damianopetrungaro** [comment]
Checked just now, it is already in place!
Closing this one, thanks @SimonKienzler for spotting it!

**Comment by SimonKienzler** [comment]
Not a problem, @bcoe basically wrote this PR for me in #138 , I just created it. Thanks for closing it. If you ever need a German translation, let me know. I'd be happy to help out again :)

**Comment by damianopetrungaro** [comment]
If you want to can add it and maintain it ;)

**Comment by SimonKienzler** [comment]
Ah, I thought there was a German translation already that just needed upkeep :D Unfortunately I do not have the time to translate the whole thing atm. As far as I'm concerned most German-speaking devs prefer English content anyway, so it's probably not that important.
