### ISSUE TITLE
translations for v1.0.0-beta.4 of specification

### ISSUE THREAD

**Issue by bcoe** [conventional-commits/conventionalcommits.org#142]
we're marching towards [v1.0.0](https://github.com/conventional-commits/conventionalcommits.org/pull/141) of this specification, it would be lovely to get updated translations for this.

Note, there's an additional element we need to translate, the [Quick Summary button](https://github.com/conventional-commits/conventionalcommits.org/issues/140) added by @SimonKienzler.

@seognil, @0x6368656174, @damianopetrungaro, @mascor, @SimonDevelop, @archemiro, would you be willing to help provide some updated translations; your help in the past has been greatly appreciated -- the specification will also hopefully be moving significantly slower now that we're releasing `v1.0.0`.

**Comment by leomullerbq** [comment]
To which languages do you need a translation? I can help with the pt_BR one

**Comment by seognil** [comment]
> To which languages do you need a translation? I can help with the pt_BR one

welcome and thanks to add more 😄
Check the contributing guide
https://github.com/conventional-commits/conventionalcommits.org#contributing

you can start from the latest (beta-4 now)
(well... differences between versions is not huge)
`content` is in `./content`
list `config` is in `./config.yaml`

**Comment by bcoe** [comment]
what @seognil said :smile: we're open to any translations we haven't landed yet, or an extra set of eyes on the existing translations ...

I was hoping we were marching towards `1.0.0` a bit faster, but the introduction of `!` threw a monkey-wrench in things ... I'm quite loving the `!` addition to the spec however.

**Comment by damianopetrungaro** [comment]
I am gonna have some free time (finally) hopefully I'll update the Italian translation next week!
