### ISSUE TITLE
Where shuould the exclamation mark go if there's a scope?

### ISSUE THREAD

**Issue by Woile** [conventional-commits/conventionalcommits.org#144]
Hello folks, I have 2 questions regarding `!`.

I was wondering first, how should it be used when there's a scope?

`feat(users)!: new user interface`

or 

`feat!(users): new user interface`

2. Should the `!` be mandatory? This would have 2 benefits:
* Easier to parse just the title of the commit to find if it's a `BREAKING CHANGE` or not. 
* Easier to look at the git history without having to read every description.

Cheers, looking to hear your feedback! I really like it!

**Comment by bcoe** [comment]
here's why I would hate for the `!` to be mandatory:

```
git commit --allow-empty -m "fix!: hello world"
bash:  : unrecognized history modifier
```

:point_up: `!` is a special character in `bash`, and I would find it annoying to have to escape it or remember to use single quotes every time I make a breaking change -- I also think this introduces friction for users.

I _do_ think we might be able to make the `BREAKING CHANGE` optional, if a user uses a `!`.

---

As for where to place the `!` it should be immediately before the `:` whether or not you're using a scope :+1:

**Comment by bcoe** [comment]
two more thoughts:

perhaps requiring one or the other (or allowing both) would help reduce friction? `!` ends up being a shorthand for BREAKING CHANGE, when the description portion of the commit message is enough to describe the breaking change.

Even though I quite like the `!`, should we consider using another character that isn't a special character in `bash`.

**Comment by Woile** [comment]
Wow, great feedback, agreed on all the items. Thanks! I don't which one could be used, maybe `&`?

Something to keep in mind with symbols is that it becomes less clear for someone who doesn't know the conventions. And then more symbols might be added to the convention, becoming really hard to decipher for people.

**Comment by damianopetrungaro** [comment]
@Woile feel free to open it again if you have other question :D

**Comment by locaIhost** [comment]
I can't find an answer, did you eventually come to an agreement? It's just that I ran into this problem today, too.  😺

**Comment by jmewes** [comment]
Using single quotes for the commit message doesn't cause the error.

```
git commit -m 'docs!: remove draft for architecture documentation'
```
