### ISSUE TITLE
In the "Tooling for Conventional Commits" can I add Code Editors Plugins?

### ISSUE THREAD

**Issue by gabrielizalo** [conventional-commits/conventionalcommits.org#162]
In the "Tooling for Conventional Commits" can I add Code Editors Plugins?
For WebStorm and JetBrains editors there is a plugin that helps to create Conventional Commits.

**Comment by damianopetrungaro** [comment]
Sure! Feel free to add it! Thanks for the input!

**Comment by tunnckoCore** [comment]
Hm. Just noticed. As I remember, we merged the addition of `gitcommit` (or it was the `parse-commit-message`, hm) before some months, when and why it was removed?

**Comment by gabrielizalo** [comment]
@damianopetrungaro .. And how is the process of translation... I can add the tool to english lenguaje only...

**Comment by damianopetrungaro** [comment]
@tunnckoCore maybe has been lost 😱, could you please add it again? Sorry about that!

**Comment by damianopetrungaro** [comment]
The translation will be updated only when there will be a bump on the release.
(so when the beta5 will be out all the folks who translated the specs will update it, no worries about that ;) )

**Comment by gabrielizalo** [comment]
Thanks.... The Pull Request has been merged.
