### ISSUE TITLE
Does Conventional care if the description is capitalized or not?

### ISSUE THREAD

**Issue by epage** [conventional-commits/conventionalcommits.org#176]
The current spec does not say one way or the other but all the examples are lower case and someone tells me Angular's spec required it.

**Comment by damianopetrungaro** [comment]
Het @epage  this is what we recommend :D 

https://www.conventionalcommits.org/en/v1.0.0-beta.4/#are-the-types-in-the-commit-title-uppercase-or-lowercase

**Comment by epage** [comment]
that is about the type while I'm talking about the description after the colon.

**Comment by JeanMertz** [comment]
> someone tells me

I guess that _someone_ was me? 😉 

In either case, it's mentioned [here in the Angular CONTRIBUTING.md file](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#subject):

> ### Subject
> 
> The subject contains a succinct description of the change:
> 
> * use the imperative, present tense: "change" not "changed" nor "changes"
> * don't capitalize the first letter
> * no dot (.) at the end

**Comment by bcoe** [comment]
I tend towards lower-case, but not a hill I think is worth dying on.

**Comment by bcoe** [comment]
👍 we call out in the specification that conventional commits are not case sensitive.

**Comment by denisw** [comment]
> 👍 we call out in the specification that conventional commits are not case sensitive.

Sorry to comment on such an old ticket, but as mentioned in an earlier comment, the spec only calls this out for the commit _type_, but not the _description_. It would still be helpful to tweak the first FAQ entry so that this is explicit, as I just stumbled over this point myself (it's what led me to this issue in the first place).
