### ISSUE TITLE
accepted characters for type and scope

### ISSUE THREAD

**Issue by hdevalke** [conventional-commits/conventionalcommits.org#223]
This is the definition of type and scope:

> consists of a noun

It is unclear to me what are the allowed characters of a noun. Is it limited to ascii word characters, can it have numbers, underscores, dashes?

**Comment by tunnckoCore** [comment]
Good point. I guess everything is allowed. It can be seen that some add the package name in the scope like `fix(@scope/pkg-name): foo bar`, so..

In javascript land, it's probably easy to guess that what's supported as `name` that's supported as scope. 

But yea, good question, I'm wondering almost every time, haha.

**Comment by bcoe** [comment]
@hdevalke @tunnckoCore what if we use the term `identifier` rather than `noun`, and then explicitly define this?

**Comment by hdevalke** [comment]
@bcoe That would be better indeed. Maybe a formal grammar of conventional commits could be helpful as well, see [semver.org](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions).

**Comment by SirWindfield** [comment]
If we're already there: What about any valid unicode character that is not ')'? So for example, Japanese, Korean etc. would work as well. Numbers are included, emoji. It just has to terminate with a `)` and does not contain newline characters 🤔

**Comment by damianopetrungaro** [comment]
Good point on @SirWindfield

**Comment by SirWindfield** [comment]
The same could be applied to the type, however, that does bring up the question: What about `fix` and `feat`? Should they be translated into other languages as well? For example, Japanese does normally not use our alphabet letters. How would those languages get handled? 

Or would `fix`, `feat` be "locked in" into English as they are right now? :)

**Comment by tunnckoCore** [comment]
@SirWindfield yea, I think that they definitely should be locked. I see CC as _conventional standard_, not _a framework_. The difference is that in "conventional standard", there're some locked things and terms, and rules, a convention. If you look at it as "framework" it just draws some frame and suggestions and allows _interpretation_ (in this case different language). 

The beauty in the software industry is that English is THE language and everyone can understand it, or at least should in basic level, not to mention the Google Translate which is quite good these days. And... in this global world, almost everyone knows at least 2 or 3 languages.

Another strong point against such transliteration is that if we allow it, it will be harder for other non-japanese (or whatever) people to understand what's happening. If we don't at least we will know is it a fix or what.

**Comment by SirWindfield** [comment]
Good points @tunnckoCore!

I do agree on the lock, I just wanted to gather other opinions :) That being said, is there some RFC process involved for making changes to the specification (or maybe something like "extensions"). The "unicode" extension for example 🤷 :D

**Comment by tunnckoCore** [comment]
I think there's no RFC process, but we are commenting/voting/sharing our thoughts on the issues and PRs, plus the other members have a higher view on the community users even outside the JavaScript.

**Comment by vlad0337187** [comment]
Hello.

1. Are points allowed as scope identifiers right now ?
like:
`feat(users.seeds): add admins"

2. Can word `feature` be used instead of `feat` ?
(according to [clause 14 of specification](https://www.conventionalcommits.org/en/v1.0.0/#specification), types other than feat and fix MAY be used in your commit messages, e.g., docs: updated ref docs. )

Thanks.

**Comment by damianopetrungaro** [comment]
1) YUP! I do it often :)
1) YUP! If you do like more verbose names

Il mer 23 set 2020, 21:42 Vladislav <notifications@github.com> ha scritto:

**Comment by bcoe** [comment]
:wave: we've been pulling together a formal grammar for Conventional Commits:

https://github.com/conventional-commits/parser#the-grammar

This grammar defines tokens explicitly, as unicode characters with some exceptional tokens depending on context (e.g., `:` and `(` in the header).

Let's move conversation to the parser repo.
