### ISSUE TITLE
refactor example isn't a refactor

### ISSUE THREAD

**Issue by gabrielf** [conventional-commits/conventionalcommits.org#229]
The [example of a refactor](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both-and-breaking-change-footer) is

> refactor!: drop support for Node 6
>
> BREAKING CHANGE: refactor to use JavaScript features not available in Node 6.

But is this really a refactor? I guess people have slightly different definitions of refactoring but Wikipedia says (emphasis mine):

> Code refactoring is the process of restructuring existing computer code—changing the factoring—**without changing its external behavior**

With that definition you cannot have a refactor commit that also contains a breaking change.

I think the example should be changed to something like:

> refactor: extract foo function to reduce duplication

The example containing `!` could be changed to a `feat:`.

**Comment by stevemao** [comment]
I agree this is not the best example. And previously you couldn't include breaking changes in refactor but we loosen the rule a bit. Maybe we could write a better example of refactor and use either `feat` or some custom tag to demonstrate `!`

**Comment by shaman-apprentice** [comment]
> And previously you couldn't include breaking changes in refactor but we loosen the rule a bit

May I ask, why did you loosen it? From my point of view it should definitely not be allowed, as a refactor prohibits breaking changes by definition.

**Comment by damianopetrungaro** [comment]
@gabrielf good one tho!
Wanna open a PR using `feat` in the examples you pointed out?

**Comment by javier-godoy** [comment]
I agree that the new example is easier to understand, however:

@gabrielf 
> Code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior

@shaman-apprentice 
> A refactor prohibits breaking changes by definition.

How would you call a change that renames a function? Assume that the function is part of the public API, thus renaming it is a breaking change.  It doesn't change its "external behavior" either (unless the function name is considered part an attribute of the behavior).
