### ISSUE TITLE
git template implementing conventional commits

### ISSUE THREAD

**Issue by zakkak** [conventional-commits/conventionalcommits.org#235]
Hello,

I just wanted to mention that providing a git template like [this one](https://gist.github.com/Linell/bd8100c4e04348c7966d) would significantly lower the entry barrier for command line users.

What are your thoughts?

**Comment by tunnckoCore** [comment]
Maybe :)

**Comment by erdaltsksn** [comment]
https://github.com/erdaltsksn/dotfiles/blob/master/git/.gittemplate

This is my template used by all of my repositories.

Also you can add my [Vim](https://github.com/erdaltsksn/dotfiles/blob/master/vim/ftplugin/gitcommit.vim) plugin to start Git commit in insert mode and make the color red when the line is too much.

**Comment by damianopetrungaro** [comment]
We can discuss more about this here #283 , so we can hava goal of adding a template as well ;)
