### ISSUE TITLE
Letter case for description

### ISSUE THREAD

**Issue by mark-rushakoff** [conventional-commits/conventionalcommits.org#238]
It looks like conventional commits do not explicitly specify whether a description should begin with an uppercase or lowercase letter, although all the examples appear to begin with a lowercase letter.

Could the next revision recommend that the description starts with a lowercase letter? Something like:

> A description SHOULD begin with a lowercase letter, except when the first word would normally begin with an uppercase letter, such as a proper noun or acronym.

**Comment by damianopetrungaro** [comment]
IMHO there isn't a benefit of putting it on the specs itself.
But I'd 👍  a line saying "it is cool to use both, but try to be consistent if possible".
What do you think?

**Comment by tunnckoCore** [comment]
@damianopetrungaro agree.

@mark-rushakoff, also, this allows things like `commitlint` exist.

Close?

**Comment by damianopetrungaro** [comment]
Yup gonna close due to inactivity, if we see some demand for this we can add some info in the FAQ section!
