### ISSUE TITLE
Case of commit messages

### ISSUE THREAD

**Issue by dijonkitchen** [conventional-commits/conventionalcommits.org#24]
Why does the spec have lowercase as the default? I figure as a title for a commit, it'd be uppercase. 

Reference:
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by stevemao** [comment]
It was defined by the angular convention spec.

**Comment by dijonkitchen** [comment]
I looked at the [Angular commit spec](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#)  but couldn't find a reason why though. The only thing I could guess would be that it's easier to parse, but lowercase looks off as the start of all the Subject lines.

**Comment by stevemao** [comment]
I guess it's just easy to type. no particular reason. But good to have consistency.

**Comment by dijonkitchen** [comment]
I figure the best practice if we're setting a standard is capitalized.

For example:
```
Build(npm): Upgrade npm version
```

**Comment by bcoe** [comment]
@stevemao @dijonkitchen joining this conversation late ... could we make our default parser for conventional commit messages not care about case? seems like it's not something worth being opinionated about.

**Comment by dijonkitchen** [comment]
Sure, that makes sense to me! Though I think uppercase looks better for readability, the parser for the changelog should be agnostic!

**Comment by stevemao** [comment]
I'm not opposing anyone here :) I see more people typing lower cased sentences in the commit messages in general. Also I've always wanted tools like conventional-changelog auto capitalise the first letter in a sentence.

**Comment by damianopetrungaro** [comment]
I prefer lowercase too, do we need something for this?

**Comment by hbetts** [comment]
My two cents:
* Parser should not care.
* Capitalization should be enforceable per-project through `commitlint`.
* Format of changelogs should be opinionated/consistent.
* `commitlint` defaults should align with default of Conventional Commits.

As for whether the type, and first word of the summary, should be capitalized, I have no opinion on one way or another. Can someone do a quick grep over GitHub to find what's commonly used?

**Comment by hbetts** [comment]
To move this forward, should we add an item to the _FAQ_ that acknowledges that any casing may be used?

**Comment by damianopetrungaro** [comment]
@hbetts Yup, totally agree with it!
@dijonkitchen do you want to work on it?

**Comment by dijonkitchen** [comment]
Boom! ☝️

**Comment by mlindner** [comment]
This is utterly broken. Please study https://chris.beams.io/posts/git-commit/#capitalize

**Comment by annanyearian** [comment]
> 3. Capitalize the subject line

Even trying to follow existing git best practices it's not clear to me if the subject line includes the type and scope like some people here suggest. If you treat type and scope as technical constants then the initial capital should be at start of the sentence after the colon.

> Fix(Reporting): Change CIFS read failure code to correct READ_ERR
> Fix(reporting): Change CIFS read failure code to correct READ_ERR
> fix(reporting): Change CIFS read failure code to correct READ_ERR
> fix(reporting): change cifs read failure code to correct READ_ERR

Having acronyms lowercase looks strange, but so does starting a sentence with lowercase change. The original angular does thankfully have acronyms and proper nouns capitalised. Currently I use 2nd line above, but thinking to change to 3.

**Comment by Arcitec** [comment]
There's only one thing that makes sense to me: Putting the Conventional Commit tag at the start and then writing a normal best-practices commit message after that.

Meaning:

- `fix(reporting): Change CIFS read failure code to correct READ_ERR`
- `lowercase-type(scope): Sentence cased description`
