### ISSUE TITLE
What about different commit types and then squashing and merging?

### ISSUE THREAD

**Issue by jacek-jablonski** [conventional-commits/conventionalcommits.org#259]
Hi!

How does different commits with different message types relate to later squashing and merging?

History on branch looks like:

1. fix: something
2. docs: add to docs
3. feat: added feature A

Later during squash and merge should I create completely new summarized message ignoring f.e. `docs:` or `fix:`?

**Comment by damianopetrungaro** [comment]
You should not squash merge 3 commits meant to solve 3 different problems.
You can use 3 pull request each one with 1 commit, or 1 pull request with 3 commits, both of them without squashing commits :)
