### ISSUE TITLE
Web site doesn't show 1.0.0

### ISSUE THREAD

**Issue by jskeet** [conventional-commits/conventionalcommits.org#260]
As noted in #200, version 1.0.0 of the spec has shipped. The [content is even present](https://github.com/conventional-commits/conventionalcommits.org/tree/master/content/v1.0.0).

Unfortunately, https://conventionalcommits.org redirects to https://www.conventionalcommits.org/en/v1.0.0-beta.4/, and https://www.conventionalcommits.org/en/v1.0.0 gives a "page not found".

Hopefully this is a simple matter of fixing a config entry as mentioned by @damianopetrungaro.

**Comment by damianopetrungaro** [comment]
Fixed on #261 
Still missing where it got deleted tbh 👀

**Comment by ben-mckernan** [comment]
Does this need to be reopened? I'm getting 404 on https://www.conventionalcommits.org/en/v1.0.0 again.

**Comment by damianopetrungaro** [comment]
Yes please, let me take a look ASAP

**Comment by damianopetrungaro** [comment]
Looks like it is solved, sometimes the build is not idempotent.
I need to debug HUGO for that (or the theme), thanks for letting me know!
