### ISSUE TITLE
RFC Specify issues for better design choices

### ISSUE THREAD

**Issue by matu3ba** [conventional-commits/conventionalcommits.org#263]
I do very much like your choices for commits, but I am missing a convention/specification for issues.
Below is a combination of bug/rfc that is common in project structures open for comment.

Reason: estimation of cost (maintainability vs gain) is underspecified for technical reasoning in the merge commit

Context: Merge commits tell you nothing about the technical basis of the decision to the code. Hence you leave the code design part completely out and end up making poor choices or leave others to make it unnecessary hard to learn from your design mistakes.

Please provide feedback on the idea.
```

bug/rfc: description

expect: outcome description

related: none/#issuenumber

code: input
---
code/steps
---

expect: output
---
result
---

kernel: win10/win7/linux4.4/linux5.7/mac10.0/mac10.15

version: `program --version`/`git rev-parse HEAD`

interaction: none/program list

context: additional setup/run inside virtual machine with special libraries etc/links, text and further literature
behavior of similar programs

perf: impact

performance

usability

maintainability
```

**Comment by matu3ba** [comment]
Aside I noticed you have no fields for the meaning `usability` and `maintainability`, which are essential to code bases.

**Comment by damianopetrungaro** [comment]
Hey @matu3ba I'd suggest you create a new project for that since conventional commits have as main focus fixing commits and not PR or bugs.

Sorry for not being able to help you on that <3
