### ISSUE TITLE
feat(website): Add favicon-s

### ISSUE THREAD

**Issue by karol-depka** [conventional-commits/conventionalcommits.org#275]
![image](https://user-images.githubusercontent.com/958486/83958623-365da180-a874-11ea-94e9-d69c7c581e06.png)

I can do it.

**Comment by damianopetrungaro** [comment]
Yes, please! I'd love it!
Are you on it @karol-depka ?

**Comment by karol-depka** [comment]
> Yes, please! I'd love it!
> Are you on it @karol-depka ?

Hi.
Cool.
Can You provide some graphics / logo?
Ideally in vector format, ideally in svg.

**Comment by karol-depka** [comment]
Or should I make some graphic for favicon?

Idea: CoCo (from Conventional Commits) e.g. in colors/style of a coconut. Just an idea, not sure if not too cheesy/fancy ;). Plz lmk.

**Comment by karol-depka** [comment]
For square favicon, 2 line layout:

Co
Co

**Comment by karol-depka** [comment]
Possible variatios of second line being rotated/mirrored for symmetry and fanciness. Plz lmk how fancy/simple we want it to be :).

**Comment by karol-depka** [comment]
Or ConCom

Con
Com


Ehm but would look/sound too much like C*ndom ;)

**Comment by karol-depka** [comment]
@damianopetrungaro or You want to use the circle logo as on https://github.com/conventional-commits
?

**Comment by karol-depka** [comment]
In any case, You can assign me to this issue.

**Comment by damianopetrungaro** [comment]
Assigned :)

**Comment by damianopetrungaro** [comment]
I think we may use the same circle we use for the github org! @karol-depka

**Comment by damianopetrungaro** [comment]
Any update @karol-depka ?
