### ISSUE TITLE
breaking change does not bump major

### ISSUE THREAD

**Issue by ashton** [conventional-commits/conventionalcommits.org#278]
Hello! I'm using lerna version with --conventional-commits option, and following the description on your website for a breaking change, copying and pasting the same commit message does not generates a major bump:

![image](https://user-images.githubusercontent.com/95974/84699961-d24c7480-af28-11ea-9e1e-07f21bd620bd.png)

![image](https://user-images.githubusercontent.com/95974/84700026-ea23f880-af28-11ea-90f4-ec5cb20db572.png)

The changelog is generated correctly **with** the breaking change section
![image](https://user-images.githubusercontent.com/95974/84700357-68809a80-af29-11ea-9c11-b047770a8010.png)

**Comment by SirWindfield** [comment]
Shouldn't this go into the repository of the tooling instead of the specification?

**Comment by wesleytodd** [comment]
Hey @ashton, I would recommend raising this issue on the lerna repo or the conventional changelog repo as @SirWindfield suggests.

**Comment by jak-pan** [comment]
I guess that this is expected since per https://semver.org versions starting with 0.x.x are considered pre-release and during that period anything can change until you release a first stable version starting with 1.0.0 @ashton
