### ISSUE TITLE
Add commit type recommendations with examples as an own block

### ISSUE THREAD

**Issue by Zerotask** [conventional-commits/conventionalcommits.org#282]
At the moment there are just the 2 mandatory commit types **fix** and **feat**. Personally I also follow the recommended other commit types from point 4
> 4. Others: commit types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the Angular convention) recommends chore:, docs:, style:, refactor:, perf:, test:, and others.

There is an external link to the Angular convention which shows a better overview of the recommended commit types.

![grafik](https://user-images.githubusercontent.com/20150243/87296909-d65bba00-c507-11ea-9f45-3522f5d7a534.png)

My suggestion is to add a block (**Recommended commit types**), similar to that from the Angular convention to the definition (index.md) to give a short summary / explanation of each recommended commit type

**Comment by damianopetrungaro** [comment]
Looks like #283 
We can discuss it there tho :)
Love this one tho, amazing idea @Zerotask !
