### ISSUE TITLE
deploying website is currently broken

### ISSUE THREAD

**Issue by bcoe** [conventional-commits/conventionalcommits.org#291]
Deploying the latest version of the website breaks link to `v1.0.0`.

**Comment by damianopetrungaro** [comment]
@bcoe which one is broken?

**Comment by bcoe** [comment]
@damianopetrungaro I did a bisection at one point, I will need to dig it up. It's a change that shouldn't break anything, so I'm pretty convinced it's something broken in HUGO not anything  we landed.

**Comment by damianopetrungaro** [comment]
Nice, let me see if you identify something I know quite well Go and I (we) may submit a PR to HUGO as well

**Comment by bcoe** [comment]
@damianopetrungaro it seemed like when we deployed [this version of the site](https://github.com/conventional-commits/conventionalcommits.org/commit/9807d999af7cbc8778bc0bb274324f64d612e1a7) we suddenly stopped rendering `v1.0.0`.

I have the deploy pinned to an older version right now.

**Comment by bcoe** [comment]
@chonla thank you for the contribution, this seems worth a shot at least 😄

**Comment by bcoe** [comment]
@chonla it seems like that's fixed the deployment \o/ thank you.
