### ISSUE TITLE
Please introduce wtf: type

### ISSUE THREAD

**Issue by tobimx** [conventional-commits/conventionalcommits.org#298]
You stumble over so much annoying/time-consuming nonsense ...

AC:

- Improve and replace the ordinary type `fix` when fixing a 🐛 on given circumstances.
  You spent so much time for this tiny peace of code - alias "it ruined my day to find it"
- let me express my anger

**Comment by wesleytodd** [comment]
Hey @tobimx! I totally feel the pain here 🤣.  Also, as you can imagine this is not something I think would be seriously added to the spec.  You can always use it in your own projects, as the spec allows for alternate tags.

cc: @bcoe It looks like I don't have triage permissions.  Could we put together a triage group on the org with the `triage` role for all repos?

**Comment by tobimx** [comment]
> as the spec allows for alternate tags.

👍
