### ISSUE TITLE
Allow to use "ref" as short form of "refactor"

### ISSUE THREAD

**Issue by Snelius30** [conventional-commits/conventionalcommits.org#325]
It's most annoying long term for me. I guess it will be good to add "ref" as a short form.

Propose as equal form
`refactor(CClass): Remove params`
and
`ref(CClass): Remove params`

**Comment by nikolay** [comment]
It's ambiguous as 'ref' abbreviation means only 'reference.'

**Comment by Snelius30** [comment]
'reference' is out of context there

**Comment by MohammedNoureldin** [comment]
I would say `refa` or `refac`, as for me it does not make sense to use `feat` instead of feature, while `refactor` is longer than feature.

In general, I find all prefixes are relatively long and not consistent (different char count).

**Comment by nikolay** [comment]
@MohammedNoureldin If most of your commits are refactorings, that this is an indicator that you need to revisit your process.

**Comment by MohammedNoureldin** [comment]
@nikolay , no it is not. But this is not my point. My point is, it makes no sense to use `feat` instead of `feature` (7 chars), while using `refactor` (8 chars) as a full word.

**Comment by Conaclos** [comment]
rejig?

**Comment by nikolay** [comment]
@MohammedNoureldin The difference is that there's an established abbreviation of `ref` meaning `reference`! Meanwhile, `feat` even outside of the domain of computer science means `feature`. No need to invent new abbreviations - the English language has enough already!

**Comment by SmartManoj** [comment]
**Proposal:** Adopt "rftr" as a shorthand for "refactor" in commit message conventions.

**Benefits:**
- **Conciseness:** "rftr" is shorter, making commit messages more efficient.
- **Consistency:** Follows a similar pattern to existing types like "feat"
- **Clarity:** Distinct from "ref," reducing potential confusion.

This change could enhance the commit message structure. Feedback and discussion on this proposal are welcome. Adjustments to better fit specific needs are encouraged.

**Comment by nikolay** [comment]
@SmartManoj "Premature optimization is the root of all evil." You're creating more problems than you're solving - now there's AI autocompletion in the terminal if you're too lazy to type 4 more characters! No English speaker will guess that "rftr" stands for "refactor," just like no English speaker will assume that "ref" stands for "refactor"! Also, typing is a form of exercise that burns calories - embrace this opportunity!

Do not try to draw parallels with "feat," which is a standard English abbreviation like "doc"!

**Comment by SmartManoj** [comment]
Thank you for your feedback. I understand your concerns, especially regarding potential confusion and the use of AI autocompletion tools. The intention behind proposing "rftr" wasn't to replace clarity with brevity but to introduce a shorthand that could become consistent and recognizable within a specific team or project context, much like how "feat" has been widely adopted.

While "rftr" may not be immediately intuitive, consistent use within a team could establish its meaning, just as other shorthand conventions have been accepted. The goal is to create a pattern that aligns with existing practices like "feat" while improving efficiency for those who prefer or need shorter commit messages. Of course, adopting this shorthand would be entirely optional and dependent on team consensus.

Since you mentioned AI autocompletion in the terminal, could you recommend a tool that effectively handles these scenarios? It might be a valuable addition to our workflow as well.

Looking forward to your thoughts!

**Comment by nikolay** [comment]
@SmartManoj Again, `feat` [1] and `doc` [2] are standard abbreviations. Also, `feat` is also a word - maybe, in this case, it wasn't even meant to mean `feature` but
```
faet n. A noteworthy or extraordinary act or achievement, usually displaying boldness, skill, etc.
```
I would never remember `rftr` as it doesn't follow the English rules for abbreviations!

[1]: https://www.merriam-webster.com/dictionary/feat

[2]: https://www.merriam-webster.com/dictionary/doc

**Comment by nikolay** [comment]
@SmartManoj Last but not least - one must be able to read good abbreviations as a word, for example, `ASAP` and `SQL`. Good like with `rftr`!

**Comment by SmartManoj** [comment]
Thank you for your feedback. You’ve made some excellent points about the nature of abbreviations. However, I’d like to clarify that "rftr" is intended as shorthand, not a strict abbreviation. The goal is to create a concise form that, while not conforming to traditional English abbreviation rules, serves a functional purpose within a team's specific context.

Shorthands like "rftr" are designed to improve efficiency and consistency within a project, even if they don't follow conventional abbreviation norms or spell out a word phonetically. The idea is that, over time, "rftr" can become easily recognized within an environment, much like other project-specific conventions.

That said, I understand the importance of intuitive and recognizable forms. However, after reconsidering, I believe "rftr" still suits the needs by being concise and distinct.

If you have any further thoughts or suggestions on this, I'd be glad to discuss them!

Thank you again for the valuable discussion!

**Comment by nikolay** [comment]
@SmartManoj There are many FOSS tools for expanding shorthand codes into text, and Espanso [1] comes to mind. Let's not allow "convention commits" to become "cryptic commits." Language and unambiguity are crucial considerations.

[1]: https://espanso.org/

**Comment by SmartManoj** [comment]
Thank you for your input. I completely agree that clarity and unambiguity are vital when it comes to committing messages. While the intention behind proposing "rftr" was to create consistent and efficient shorthand within a specific context, I understand the concern about potentially making commits less readable.

The mention of tools like Espanso is a good point; however, it's important to note that Espanso is a text expander, not a text predictor. I’m using AutoHotKey for text expansion. These tools can help expand shorthands while maintaining clarity. However, I believe there’s a balance to be struck between efficiency and readability, and it's essential to ensure that any shorthand adopted doesn’t compromise the comprehensibility of the commit messages. 

Similarly, the shorthand "msg" for "message" might seem cryptic at first, but it can become second nature with consistent use, just like "rftr." The goal isn't to create "cryptic commits" but rather to streamline the process while retaining clarity. If "rftr" or "msg" risks being too obscure, I’m open to reconsidering their use or finding ways to ensure they remain clear to everyone involved.

I appreciate your perspective and would love to continue the discussion to find the best solution.

Thank you again for your valuable insights!

**Comment by SmartManoj** [comment]
I am asking something like [this](https://www.microsoft.com/en-in/edge/features/text-prediction?form=MA13FJ) that suggests `refactor` for `ref`.

![image](https://github.com/user-attachments/assets/2f3bf8de-195d-4f56-a8c4-ea64f6229e1b)
