### ISSUE TITLE
new tool for tooling section

### ISSUE THREAD

**Issue by Sulaiman-SM** [conventional-commits/conventionalcommits.org#327]
Hi, I have created a python tool called **enforce-githooks** to help teams and individuals standardize commit messages, please add it in tooling section https://github.com/Sulaiman-SM/enforce-githooks

**Comment by bcoe** [comment]
@Sulaiman-SM go ahead and create a PR for the new tool, and we will happily add it.

**Comment by Sulaiman-SM** [comment]
@bcoe Thanks for the reply, I have already submitted a PR, waiting for the merge.
Thanks again
