### ISSUE TITLE
Fix on not released feature

### ISSUE THREAD

**Issue by samds** [conventional-commits/conventionalcommits.org#332]
Hi,

I'd like to use conventional commit in a project but I don't know how to handle the following scenario:

I have a commit that corresponds to the version 1.0.0 of my product. 
```
feat: Adds feature A
```

Now, I'm developing a new feature
```
feat: Adds feature B
feat: Adds feature A
```

I decide to give my user an alpha version 1.1.0-alpha.1. The release note should look like
```
My Product version 1.1.0-alpha.1
New Features:
Adds feature B
Bug Fixes:
None
```

I fix an issue
```
fix: Fixes an issue in feature B
feat: Adds feature B
feat: Adds feature A
```
and release another alpha
```
My Product version 1.1.0-alpha.2
New Features:
None
Bug Fixes:
Fixes an issue in feature B
```

Finally, I'm happy and I want to do a production release
```
My Product version 1.1.0
New Features:
Adds feature B
Bug Fixes:
Fixes an issue in feature B
```

While I want the fix to appear in the release note 1.1.0-alpha.2, I don't want it in the final release note 1.1.0.

How do you guys handle such case?

Thanks,
Sam

**Comment by nedbat** [comment]
Hand-authored release notes?

**Comment by damianopetrungaro** [comment]
@samds  Not sure how much it does fit within this repo since this is a specification-only repo.

Not sure how much @nedbat helps since I feel confident this is something which _can_ be automated, but still, in a another which creates release note.

Do you have any link about the releaser you're using?

**Comment by samds** [comment]
@nedbat @damianopetrungaro For now, I do my release note by hand.
I have been using the type `miss:` to express a fix on a not released feature but I guess I'm missing something. I'll close this topic because obviously the problem is me and not the specification 😊.
