### ISSUE TITLE
Guidance for a security type

### ISSUE THREAD

**Issue by feanil** [conventional-commits/conventionalcommits.org#341]
While adopting this spec one thing that stood out was the lack of a `security` type in the standard.  Is there a best practice for this?  Or would the committee be open to adding some guidance around how to manage security fixes?

**Comment by damianopetrungaro** [comment]
@feanil the only "standard type" are feat or fix, you can add as many custom types as you want in your own project :)

**Comment by damianopetrungaro** [comment]
Gonna close it, if you still have questions or doubts please let me know!

**Comment by d-damien** [comment]
I'm about to start using as I think it deserves its own type indeed, given the importance of security in CS. Seeing as other types are all short − perf, doc etc. − I'll take `sec`.
