### ISSUE TITLE
Improve example "Commit message with multi-paragraph body and multiple footers"

### ISSUE THREAD

**Issue by shaman-apprentice** [conventional-commits/conventionalcommits.org#348]
As a developer I want commit messages to be succinct and readable. As a user of Conventional Commits I want the examples to be clear and inspiring to use the guidelines.

I had to read the given example below [Commit message with multi-paragraph body and multiple footers](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers) multiple times to understand, that both bodies are one connected sentence. 

> fix: correct minor typos in code
> 
> see the issue for details
> 
> on typos fixed.
> 
> Reviewed-by: Z
> Refs #<span/>133

I think it is more intuitive to write the two bodies as one, which is more readable than splitting one sentence over 3 lines.

What do you think about updating the example, so that each body is a sentence with a separate meaningful concern by itself? Maybe:

> refactor: implement observer pattern
> 
> this makes it easy to add new observers in the future.
> 
> see \[architecture](link-to-architecture-documentation) for further details.
> 
> Reviewed-by: Z
> Refs #<span/>133

**Comment by derekmurawsky** [comment]
I second this, and would take it a step further by possibly incorporating some of the ideas around what makes a good commit message. I have used [this blog post by Chis Beams](https://chris.beams.io/posts/git-commit/) as the basis of my commit messages for a while now and have found it to be an excellent pattern. The key aspects are:

1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Use the imperative mood in the subject line
6. Wrap the body at 72 characters
7. **Use the body to explain what and why vs. how**

That last point, number 7, is huge to me. If nothing else is incorporated to conventional commits, I would encourage you consider that. Issues trackers can change over time. Commit histories are, generally, forever.

**Comment by damianopetrungaro** [comment]
@shaman-apprentice I agree with you, do you wanna open a  PR for that?

**Comment by derekmurawsky** [comment]
> @derekmurawsky At the moment the convention is totally open to provide support to most of the tooling around, I agree with you that those are really good rules for writing a commit message, but still, I'd consider those not mandatory for the current state of the specification.

Thanks for the reply!

To clarify, I meant that we should either reference the other work or improve **_the example_**. I did _not_ mean it should be included in the standard itself.

And I don't mean to speak for @shaman-apprentice - But I believe they were referring to the examples as well.

**Comment by damianopetrungaro** [comment]
Then it’s totally ok! If you want you can open a PR and fix that! I’d love
it :)

**Comment by shaman-apprentice** [comment]
I am just writing quickly from train and I don't want to rush.  Thanks for your comments! I will gladly create a PR in the next days.
