### ISSUE TITLE
What is the genral convention for mixed commit message.? eg:  if a commmit contains refractor, fix and style changes.

### ISSUE THREAD

**Issue by j0hn5on** [conventional-commits/conventionalcommits.org#374]
What is the general convention for mixed commit message.? eg:  if a commit contains refractor, fix and style changes. Does the fix gets the highest priority.?

**Comment by VibingCreator** [comment]
From my understanding, the whole key is to make more commits. Just avoid such situations, commit every change.

**Comment by damianopetrungaro** [comment]
That's the point tho!
Making more commit, smaller with a more declarative and easy-to-understand scope, is the way to go!

Gonna close this, @j0hn5on feel free to reopen if you have any follow up question :D
