### ISSUE TITLE
What is the approach for initial commits?

### ISSUE THREAD

**Issue by VibingCreator** [conventional-commits/conventionalcommits.org#375]
I have seen people using different ways to approach initial message commit:

`chore: initial commit`

`feat: initial commit`

`initial commit`

**Comment by damianopetrungaro** [comment]
This is an old and frequent question!
The answer is... you decide!

The important point to me is related to the clarity of the commit message, if it expresses the purpose then it's good ;)
https://github.com/conventional-commits/conventionalcommits.org/issues/109

If you have other qquestion feel free to repoen the ticket :)
