### ISSUE TITLE
Recommend imperative present tense

### ISSUE THREAD

**Issue by intelliot** [conventional-commits/conventionalcommits.org#388]
There was a [PR](https://github.com/conventional-commits/conventionalcommits.org/pull/85) that added this to the FAQ, but the question/answer is missing in the current 1.0.0 release.

**Comment by SergeiKuznetsov** [comment]
It was removed in [this commit](https://github.com/conventional-commits/conventionalcommits.org/commit/87d94e3a#diff-e47a94494da821ef7bd10cb39a22c6617bbfcb0748eaabae9884b38bd5ab0421L159-L164). 
@damianopetrungaro committed on Sep 16, 2018

**Comment by damianopetrungaro** [comment]
@intelliot @SergeiKuznetsov do you wanna open a PR to fix that? It would be super appreciated :)
