### ISSUE TITLE
Add a list of known projects using Conventional Commits

### ISSUE THREAD

**Issue by jeremyfiel** [conventional-commits/conventionalcommits.org#427]
I believe this will help drive adoption and give clarity where using the specification has benefited those projects/companies

**Comment by bcoe** [comment]
@jeremyfiel there's a list here on the About page:

https://www.conventionalcommits.org/en/about/

☝️ is that what you had in mind?

**Comment by jeremyfiel** [comment]
i added my own contribution.  #428
