### ISSUE TITLE
How to run project locally

### ISSUE THREAD

**Issue by cocoeyes02** [conventional-commits/conventionalcommits.org#441]
I think I cannot run project locally now. because those error happen.

- gyp verb check python checking for Python executable "python2" in the PATH
- syntax error by no supported node version

Can you run project locally now?
If you can run project locally now, I close this PR https://github.com/conventional-commits/conventionalcommits.org/pull/431.
but I wanna know why I cannot run project locally now.

If you cannot run project locally now, please review this PR https://github.com/conventional-commits/conventionalcommits.org/pull/431.

**Comment by damianopetrungaro** [comment]
Now should be working thanks to @lorenzodianni  PR.

Thanks for the issue as @cocoeyes02 hope you can enjoy a nicer developer experience 😄
