### ISSUE TITLE
Ticket/Issue ID

### ISSUE THREAD

**Issue by jamesgeddes** [conventional-commits/conventionalcommits.org#451]
Where should the issue ID go? Is there a convention for what the tag should be?

Would this be satisfactory?

```
fix: title

body

issue: {id}
```

**Comment by damianopetrungaro** [comment]
Hey @jamesgeddes there is an example on the website you could use as a reference:
```
fix: prevent racing of requests

Introduce a request id and a reference to latest request. Dismiss
incoming responses other than from latest request.

Remove timeouts which were used to mitigate the racing issue but are
obsolete now.

Reviewed-by: Z
Refs: #123
```
you could add `Issue: id` as a footer element :)

**Comment by jamesgeddes** [comment]
Thanks @damianopetrungaro - I had seen that but it seemed like this is for git IDs, so I was just wondering if it would be permissible to make up a tag. We will do as you have suggested! Thanks!
