### ISSUE TITLE
Merge Commits

### ISSUE THREAD

**Issue by dsbert** [conventional-commits/conventionalcommits.org#454]
Is there any recommendation for how merge commits should be formatted?

My team uses gitlab, which generates merge commits with the following default template.

```
Merge branch '%{source_branch}' into '%{target_branch}'

%{title}

%{issues}

See merge request %{reference}
```

I was considering the following.

```
merge: '%{source_branch}' into '%{target_branch}'

%{title}

%{issues}

Merge-request: %{reference}

```

**Comment by damianopetrungaro** [comment]
Hey @dsbert !
merge commit _should_ not exist IMHO :) 

I do suggest you take a look at the rebase merge, which fixes the issue of having merge commits.

**Comment by MAHDTech** [comment]
In GitLab you can also change the default to Fast-forward merge to stop those commit appearing.

![image](https://user-images.githubusercontent.com/16071195/176578504-2eb7cf63-9d8d-4d9c-90b3-c1bc17da0d8c.png)

**Comment by damianopetrungaro** [comment]
Closing this, @dsbert let me know if you have any other doubt!
