### ISSUE TITLE
Release notes are the same with every release

### ISSUE THREAD

**Issue by raul1991** [conventional-commits/conventionalcommits.org#460]
I am using the following to generate complete release notes which is working as expected.

```
./node_modules/.bin/conventional-changelog --preset conventionalcommits --infile CHANGELOG.md --append --same-file --release-count 0
```
but when I don't give --release-count option, I expect it to give me release notes only for 1 release but it still outputs the entire thing.

I have tagged my release after generating the complete release notes.

**Comment by damianopetrungaro** [comment]
@raul1991 I think you opened the issue in the wrong repository :) 
Closing, for now, let me know if you need help with the conventional commit specification
