### ISSUE TITLE
Experiment as a commit type

### ISSUE THREAD

**Issue by raquelmsmith** [conventional-commits/conventionalcommits.org#481]
We will often run experiments on language, features, flows, etc, and these don't really fit into the typical definitions. It would be nice to be able to mark something as an experiment (maybe `exp`) if that's what the commit/PR is.

**Comment by damianopetrungaro** [comment]
Hello @raquelmsmith !
Feel free to add it as your supported type :D 

The specification explains that you can, for whatever reason, use a type or a scope that is not documented, but better fits your project!

My 2 cents: Make sure you know how the `exp` type should affect releases, should it be treated as a minor or a major release?

**Comment by damianopetrungaro** [comment]
Feel free to reopen if you need to :) 
Closing it since I don't think it will supported as "standard" type anytime soon!
