### ISSUE TITLE
Fix: Alphabetical Order

### ISSUE THREAD

**Issue by WebSnke** [conventional-commits/conventionalcommits.org#494]
The project lists on [/content/next/index.md](https://github.com/conventional-commits/conventionalcommits.org/blob/master/content/next/index.md) don't seem to be sorted. Is this intentional or should this be fixed?

**Comment by damianopetrungaro** [comment]
@WebSnke  It is intentional, should be sorted by when it was added :D

**Comment by WebSnke** [comment]
> @WebSnke It is intentional, should be sorted by when it was added :D

Ok, thanks.
