### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by volehuy1998** [conventional-commits/conventionalcommits.org#495]
Can you make tutorial how to install it? Because I really want to use it but don't know how to interage it into my project.

**Comment by jalalbmnf** [comment]
I guess this is documentation, not a package

**Comment by volehuy1998** [comment]
> I guess this is documentation, not a package

Show how to use this technology? ........

**Comment by jalalbmnf** [comment]
Simple, just you have to read and start to implement what is written in this documentation.  :)

**Comment by volehuy1998** [comment]
But I'm using gitlab infra. It will apply to my gitlab?

**Comment by jalalbmnf** [comment]
It does not matter what do you using, I mean you can read this documentation and start to commit according to the documentation, that is all. You can not install or integrate anywhere this, just you have to read and practice

**Comment by damianopetrungaro** [comment]
Hey @volehuy1998 !

As @jalalbmnf suggested you can start using this when writing your git commit messages :D 


Going to close this, if you still have doubts feel free to ping me in this issue!

**Comment by jalalbmnf** [comment]
@volehuy1998 I find this https://github.com/conventional-changelog/commitlint , this may be useful for you.
