### ISSUE TITLE
Parenthesized optional scope in commit message structure

### ISSUE THREAD

**Issue by MartinSandeCosta** [conventional-commits/conventionalcommits.org#525]
Commit message should be structured as per [doc](https://github.com/conventional-commits/conventionalcommits.org/blob/master/content/v1.0.0/index.md#summary): 
```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

While these brackets are correctly indicating that said scope is to be optionally included, the specification is missing the mandatory parentheses that should surround the scope (if it exists). Maybe it can be included as:
```
<type>[(optional scope)]: <description>

[optional body]

[optional footer(s)]
```

**Comment by mentalisttraceur** [comment]
Duplicate with #473 (that one does not have a name that makes it obvious that it's about)

**Comment by MartinSandeCosta** [comment]
Duplicated by #473

**Comment by MartinSandeCosta** [comment]
Duplicated by #473
