### ISSUE TITLE
How to configre conventional-changelog-conventionalcommits 7?

### ISSUE THREAD

**Issue by markwoon** [conventional-commits/conventionalcommits.org#543]
I'm using `semantic-release/release-notes generator` with the `conventionalcommits` preset:

```
"@semantic-release/release-notes-generator",
        {
          "preset": "conventionalcommits",
          "writerOpts": {
            "commitsGroupSort": [
              "feat",
              "perf",
              "fix"
            ],
            "commitsSort": "header"
          }
```

After upgrading to 7.0.0 this no longer works.  There are no error messages.

According to the changelog

> If you are using presets indirectly, using preset name, no any changes in configuration needed, just upgrade packages to latest versions.

What do I need to change to get conventional-changelog-conventionalcommits working again?

Or is this a problem with `semantic-release/release-notes generator`?

**Comment by stevemao** [comment]
please open an issue there

**Comment by Sourav9713329689** [comment]
> मैं `semantic-release/release-notes generator`इस `conventionalcommits`प्रीसेट का उपयोग कर रहा हूँ:
> 
> ```
> "@semantic-release/release-notes-generator",
>         {
>           "preset": "conventionalcommits",
>           "writerOpts": {
>             "commitsGroupSort": [
>               "feat",
>               "perf",
>               "fix"
>             ],
>             "commitsSort": "header"
>           }
> ```
> 
> 7.0.0 में अपग्रेड करने के बाद यह काम नहीं कर रहा है। कोई त्रुटि संदेश भी नहीं आ रहा है।
> 
> चेंजलॉग के अनुसार
> 
> > यदि आप प्रीसेट का अप्रत्यक्ष रूप से उपयोग कर रहे हैं, प्रीसेट नाम का उपयोग करके, तो कॉन्फ़िगरेशन में किसी भी बदलाव की आवश्यकता नहीं है, बस पैकेज को नवीनतम संस्करणों में अपग्रेड करें।
> 
> conventional-changelog-conventionalcommits को फिर से काम करने के लिए मुझे क्या बदलाव करने होंगे?
> 
> या फिर यह किसी समस्या के साथ है `semantic-release/release-notes generator`?

https://github.com/conventional-commits/conventionalcommits.org/issues/543
