### ISSUE TITLE
GPG key not found

### ISSUE THREAD

**Issue by mariogutval** [conventional-commits/conventionalcommits.org#579]
## Description ##
When trying to commit using the conventional commits VS Code extension, the following error is being thrown
```
git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
error: cannot run gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```
This started happening after updating OS version to macOS 14.4.1

Git keeps working fine, so the issue must be related to the extension.

**Comment by LemmingAvalanche** [comment]
> Git keeps working fine, so the issue must be related to the extension.

What extension? This repo seems to only store the website.

**Comment by mariogutval** [comment]
My bad, moving it to the other repo
