### ISSUE TITLE
Bad certificate on www.conventionalcommits.org

### ISSUE THREAD

**Issue by tirithen** [conventional-commits/conventionalcommits.org#581]
The website www.conventionalcommits.org has a bad certificate (Swedish in screenshot, but error should be obvious)

![Skärmbild från 2024-04-17 14-17-12](https://github.com/conventional-commits/conventionalcommits.org/assets/245811/a34f2105-a059-4e74-9578-5587fd478862)

**Comment by amarjandu** [comment]
plz fix this asap i cant remember any of the commit conventions by heart because my little brain is full of memes.

**Comment by jwvanderbeck-Unity** [comment]
Yeah painful because so many browsers these days completely prevent you from overriding the bad certs too.

**Comment by CarpenterBug** [comment]
The website is down
![image](https://github.com/conventional-commits/conventionalcommits.org/assets/3688770/3e635b6b-bb5a-4329-8d23-082f144dcf87)

**Comment by dudil** [comment]
@tirithen / @rjaegers / @mowies - if this is critical to your CI/CD tools you can access the website using the Netlify provided URL:
[https://tender-babbage-1fbb34.netlify.app](https://tender-babbage-1fbb34.netlify.app).

I'm not part of the team here, but happen to see the same and by looking into the DNS records found this is the provided URL by Netlify which is **always secured**

**Comment by mowies** [comment]
Thanks for the hint! :)
I think we'll wait and stay on the original URL though

**Comment by aaraney** [comment]
@amarjandu and really anyone else who can't access the site, it looks like it is generated from static markdown files that are in this repo. For example, [here](https://github.com/conventional-commits/conventionalcommits.org/blob/master/content/v1.0.0/index.md) is the `v1.0.0` page.

**Comment by bcoe** [comment]
I just clicked renew on the certificate, I'm not sure what's happening here.

**Comment by aaraney** [comment]
@bcoe, the server's cert is a wildcard netlify cert `Common Name: *.netlify.app` and the alt names are `netlify.app` and `*.netlify.app`. I hope that is helpful.

**Comment by bcoe** [comment]
Netlify had timed out renewing the letsencrypt certificate and I had to manually click a button.

**Comment by amarjandu** [comment]
@bcoe thanks for your support! Appreciate you!
