### ISSUE TITLE
Add new logo

### ISSUE THREAD

**Issue by damianopetrungaro** [conventional-commits/conventionalcommits.org#73]
@bcoe  @hbetts do you remember who designed the one for `conventional-changelog`?

It would be great having a nice one for this one too.

**Comment by hbetts** [comment]
@damianopetrungaro, it was @bcoe that designed the original CC logo. Please see https://github.com/conventional-changelog/artwork/issues/2

**Comment by damianopetrungaro** [comment]
Wow @bcoe  it's a designer too 😛 
Let's create an artwork repository when we'll have a logo.

Benjamin let me know if you have some free time, otherwise, I will do it once I'll come back from my vacation 😄

**Comment by damianopetrungaro** [comment]
@hbetts  what do you think about [this](https://thenounproject.com/search/?q=commit&i=361026)?

**Comment by hbetts** [comment]
I like the icon.

My only concern is that the background within the lines, and the circle, are transparent. If the background of GitHub, or any other website, is black, the icon will become, effectively, invisible.

If the background for the lines and circle was white, the contrast between black and white would ensure that the icon, to some degree, was visible, regardless of the background color.

**Comment by damianopetrungaro** [comment]
@hbetts we can use a background color, this is not a problem 😄 

Something like https://thenounproject.com/term/commit/685193 😄

**Comment by hbetts** [comment]
@damianopetrungaro I think either is fine :+1:

**Comment by damianopetrungaro** [comment]
I propose the logo used in the new UI here #81

**Comment by damianopetrungaro** [comment]
See that no one disagree, I am going to use this logo.

Feel free to open again if you have any comment!
(This is the same the new website UI will integrate too)
