### ISSUE TITLE
Confusing wording on BREAKING CHANGE

### ISSUE THREAD

**Issue by skinny85** [conventional-commits/conventionalcommits.org#76]
The "Breaking Change" bullet point nr 3 states:

> 3. BREAKING CHANGE: a commit that has the text BREAKING CHANGE: at the beginning of its optional body or footer section introduces a breaking API change (correlating with MAJOR in semantic versioning). **A breaking change can be part of commits of any type**.

Then, the next bullet point "Others" nr 4 states:

> 4. Others: commit types other than fix: and feat: are allowed, for example (...) chore:, docs:, style:, refactor:, perf:, test:, and others. (...) Notice these types are not mandated by the conventional commits specification, and have no implicit effect in semantic versioning (**unless they include a BREAKING CHANGE, which is NOT recommended**). 

I feel like these two points are contradicting each other.

**Comment by damianopetrungaro** [comment]
@skinny85 thank you for opening the issue!

If you think they are contradicting each other it means we can find a way to put it in a better way.

I think the main point that may be confusing is that creating your own commit type (`commit types other than fix: and feat: are allowed`) you _MAY_ use `BREAKING CHANGE` in any commit message.

If you want to open a PR to put this in a different way you are welcome.
Let's see also whay @hbetts @zeke @bcoe think about it.
___ 
btw we are discussing about `BREAKING CHANGE:` itself on #43, feel free to join the discussion.

**Comment by hbetts** [comment]
My personal preference would be to remove the reference to `BREAKING CHANGE` from item (4).

I think the bolded line from item (3) is sufficient.

**Comment by damianopetrungaro** [comment]
@hbetts but in this way `and have no implicit effect in semantic versioning` is "wrong" too.

**Comment by skinny85** [comment]
I would just remove `, which is NOT recommended` from bullet nr 4 - that's the source of the contradiction for me.

**Comment by hbetts** [comment]
@damianopetrungaro thank you for pointing out that line.

In that case I like @skinny85's suggestion.

Can we go with that?

**Comment by skinny85** [comment]
@damianopetrungaro sure, I'll try to do a quick PR today or tomorrow.
