### ISSUE TITLE
First Sumary Sentence Seems Out of Place

### ISSUE THREAD

**Issue by hbetts** [conventional-commits/conventionalcommits.org#79]
The first summary sentence:

```
As an open-source maintainer, squash feature branches onto master and write a standardized commit message while doing so.
```

Seems out of place.

I land on the `conventionalcommits` website and the first sentence is talking about squashing commits (something I don't do), but only for features (so what am I supposed to do for other commit types), and only talks about `open-source maintainer`s, which seems to exclude third-party contributors to a project.

Can we just eliminate that sentence?

**Comment by damianopetrungaro** [comment]
@hbetts yup, totally agree, I already asked about it.
It was partially done with #58 but we need to rephrase this instead of removing it IMHO.

A little summary it's fine to have in place ;)

**Comment by damianopetrungaro** [comment]
This sentence too sounds strange to me:


```
In software development, it’s been my experience that bugs are most often introduced at the boundaries between applications. Unit testing works great for testing the interactions that a maintainer knows about, but do a poor job of capturing all the interesting, often unexpected, ways that a community puts a library to use.
```

**Comment by hbetts** [comment]
What needs to be rephrased, and how do you see it being rephrased?

**Comment by damianopetrungaro** [comment]
@hbetts  

The main issue is that the entire first block seems to be out of context and it's justified only by the last sentence of the entire introduction `that makes it easier to debug issues across project boundaries.`

> ~In software development, it’s been my experience that bugs are most often introduced at the boundaries between applications. Unit testing works great for testing the interactions that a maintainer knows about, but do a poor job of capturing all the interesting, often unexpected, ways that a community puts a library to use.
Anyone who has upgraded to a new patch version of a dependency, only to watch their application start throwing a steady stream of 500 errors, knows how important a readable commit history (and ideally a well maintained CHANGELOG) is to the ensuing forensic process.~
The Conventional Commits specification proposes introducing a standardized lightweight convention on top of commit messages. This convention dovetails with SemVer, asking software developers to describe in commit messages, features, fixes, and breaking changes that they make.
>
> By introducing this convention, we create a common language that makes it easier to debug issues across project boundaries.

I think it will be better:

> The Conventional Commits specification proposes introducing a standardized lightweight convention on top of commit messages.
This convention dovetails with SemVer, asking software developers to describe in commit messages, features, fixes, and breaking changes that they make, in order to create a readable commit history (and ideally a well-maintained CHANGELOG) and creating a common language that makes it easier to debug issues.

**Comment by damianopetrungaro** [comment]
@hbetts  what o you think about
```
As a software developer, I want to create a readable commit history writing standardized commit messages to make easier and explicit what changes have been applied to a project.
```
For the first sentence?

**Comment by damianopetrungaro** [comment]
@hbetts totally agree, let's reword the first section and let's remove the `introduction`.
Something like this it's fine for me:

```
# Summary:
As a software developer, I want to create a readable commit history writing standardized commit messages to make easier and explicit what changes have been applied to a project.

The Conventional Commits specification proposes introducing a standardized lightweight convention on top of commit messages.

This convention dovetails with SemVer, asking software developers to describe in commit messages, features, fixes, and breaking changes that they make, in order to create a readable commit history (and ideally a well-maintained CHANGELOG) and creating a common language that makes it easier to debug issues...

# Examples
Commit message with description...

# Specification
The key words MUST....
```

Let me know what do you think, let's see what @bcoe thinks about it, he always find some issues that we miss 😄

**Comment by damianopetrungaro** [comment]
See #91

**Comment by bcoe** [comment]
@hbetts @damianopetrungaro see my notes in #91, my concern about moving the introduction section to the top is that "Conventional Commits" is an attempt to describe a standard.

If you look at semver.org, the content immediately jumps into a functional description of what a user adhering to the standard should do. For this reason, I advocate that we opt for a first sentence that reads something like my proposal on #91:

> When writing software use a standardized commit message, such that the commit history conveys meaning to developers and can be more easily consumed by tools.

I don't see a strong argument for removing the Introduction section from the conventional commits. I modeled the original document after https://semver.org/, which uses a similar structure:

1. Summary; introducing a trimmed down version of the spec.
2. Introduction; explaining the motivation for the specification.
3. a more thorough break down of the specification.

We've done well for the past couple years using semver as a foundation for how we approach this specification. And semver.org has done an amazing job of gaining traction of the years. I see no reason for us to deviate from a pattern that's worked.

**Comment by hbetts** [comment]
> When writing software use a standardized commit message, such that the commit history conveys meaning to developers and can be more easily consumed by tools.

@bcoe I like your suggestion, though I would like to propose replace `When writing software ...` to `When contributing to a project ...` as not all participants in Open Source write software.
