### ISSUE TITLE
Application of RFC 2119

### ISSUE THREAD

**Issue by hutson** [conventional-commits/conventionalcommits.org#87]
Re-evaluate how we are applying the terminology defined in [RFC 2119](https://tools.ietf.org/html/rfc2119) in the _Conventional Commits_ specification.

Came up in https://github.com/conventional-commits/conventionalcommits.org/issues/77#issuecomment-415851108

**Comment by hbetts** [comment]
cc @bcoe

**Comment by hbetts** [comment]
I believe this issue is simply waiting on someone to have sufficient time to review the specification and ensure each use of MUST, SHOULD, etc., is being used correctly for the desired result.

**Comment by damianopetrungaro** [comment]
@hutson @zeke @raamdev @bcoe @stevemao who wants to pick this one?
I think is pretty important for us.

**Comment by hutson** [comment]
I would love to, but I just can't commit to doing the work at this time :cry:

**Comment by bcoe** [comment]
@hutson @damianopetrungaro I'll make an effort to take this on. I essentially just need to re-read `RFC 2119`, go back through our spec, and correct the usage of our terminology I believe? i.e., we care about the "Specification" section and "Summary" section only?

**Comment by damianopetrungaro** [comment]
Yup @bcoe that's it :)
