### ISSUE TITLE
Find a strategy to bump up the version

### ISSUE THREAD

**Issue by damianopetrungaro** [conventional-commits/conventionalcommits.org#90]
@conventional-commits/committee we need to find a strategy to implement a proper semantic versioning when we'll release the first version (and it's pretty close).

What I propose is to use an `upcoming` directory where we change the latest specs version and when we decide to release (thanks to the conventional commits) we'll bump up the version and release.

Any other strategy is the welcome 😄

**Comment by damianopetrungaro** [comment]
Automatically added to the new website structure!

**Comment by bcoe** [comment]
@damianopetrungaro 🎉
