### ISSUE TITLE
Add bumped as tool

### ISSUE THREAD

**Issue by Kikobeats** [conventional-commits/conventionalcommits.org#93]
Hello,

Time ago I designed [bumped](https://bumped.github.io/) for making release software easy.

In fact, It has a [bumped-changelog](https://github.com/bumped/bumped-changelog) that use conventional commits under the hood!

I want to ask if it could be added to the tools recommend. Actually, I can make the change, just not sure if it needs to be added to all content versions or just in the current version.

**Comment by damianopetrungaro** [comment]
Thank you for the question!
Yup feel free to add it into the current/next version and it will be added in the next release!
