### ISSUE TITLE
Conventional commit tooling?

### ISSUE THREAD

**Issue by gaviriar** [conventional-commits/conventionalcommits.org#95]
Hi There,

Big fan of this spec. Is there any plans or intentions on writing tooling around this spec i.e. some basic git/hg hooks which can be developed to enforce the conventional commit format?

Would this be a task/project that you would consider to be relevant to the scope of https://github.com/conventional-commits?

**Comment by damianopetrungaro** [comment]
Hello @gaviriar there's no plan, but ideas are welcome!

Anyway there are already a lot of tools that help you generate conventional commits, such as 
https://github.com/commitizen/cz-cli or https://github.com/damianopetrungaro/php-commitizen


Did you have something in mind?

**Comment by gaviriar** [comment]
Hi @damianopetrungaro, 

Yes, I had seen the commitizen repos, which look pretty sweet! Maybe they satisfy the requirements I was thinking of:

1.  The tool should be easily integrateable as a git hook or other version control hook
2.  The tool should be configurable such that a company or project can specify his/her specific formatting guidelines e.g. maybe bug/task ID required, specific keywords required

Do the tools you highlighted above to provide such a thing?

**Comment by damianopetrungaro** [comment]
You can use them everywhere you want. It depends how you want to you it.
> The tool should be easily integrateable as a git hook or other version control hook

Yup, you can
> The tool should be configurable such that a company or project can specify his/her specific formatting guidelines e.g. maybe bug/task ID required, specific keywords required

**Comment by gaviriar** [comment]
Thanks for the response. Alright then, I guess I need to dig in a bit deeper into commitizen and see if it addresses my needs. Cheers!

**Comment by hbetts** [comment]
[`conventional-commits-parser`](https://www.npmjs.com/package/conventional-commits-parser) is another tool that parses commit messages to extract things like `type`, `scope`, `issues`, etc.
